'''
Created on 29.12.2013

@author: pavel
'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vkform.ui'
#
# Created: Sun Dec 29 19:42:07 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_vkForm(object):
    def setupUi(self, vkForm):
        vkForm.setObjectName("vkForm")
        vkForm.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(vkForm.sizePolicy().hasHeightForWidth())
        vkForm.setSizePolicy(sizePolicy)
        vkForm.setMinimumSize(QtCore.QSize(800, 600))
        vkForm.setMaximumSize(QtCore.QSize(800, 600))
        self.groupBox = QtGui.QGroupBox(vkForm)
        self.groupBox.setGeometry(QtCore.QRect(5, 0, 790, 230))
        self.groupBox.setMinimumSize(QtCore.QSize(790, 230))
        self.groupBox.setStyleSheet("border-color: rgb(85, 85, 127);")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.print_pB = QtGui.QPushButton(self.groupBox)
        self.print_pB.setEnabled(False)
        self.print_pB.setGeometry(QtCore.QRect(630, 85, 141, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.print_pB.sizePolicy().hasHeightForWidth())
        self.print_pB.setSizePolicy(sizePolicy)
        self.print_pB.setMinimumSize(QtCore.QSize(141, 30))
        self.print_pB.setMaximumSize(QtCore.QSize(141, 30))
        self.print_pB.setObjectName("print_pB")
        self.repeate_pB = QtGui.QPushButton(self.groupBox)
        self.repeate_pB.setEnabled(False)
        self.repeate_pB.setGeometry(QtCore.QRect(630, 120, 141, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repeate_pB.sizePolicy().hasHeightForWidth())
        self.repeate_pB.setSizePolicy(sizePolicy)
        self.repeate_pB.setMinimumSize(QtCore.QSize(141, 30))
        self.repeate_pB.setMaximumSize(QtCore.QSize(141, 30))
        self.repeate_pB.setObjectName("repeate_pB")
        self.clear_pB = QtGui.QPushButton(self.groupBox)
        self.clear_pB.setEnabled(False)
        self.clear_pB.setGeometry(QtCore.QRect(630, 155, 141, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_pB.sizePolicy().hasHeightForWidth())
        self.clear_pB.setSizePolicy(sizePolicy)
        self.clear_pB.setMinimumSize(QtCore.QSize(141, 30))
        self.clear_pB.setMaximumSize(QtCore.QSize(141, 30))
        self.clear_pB.setObjectName("clear_pB")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(355, 20, 256, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(256, 17))
        self.label_6.setMaximumSize(QtCore.QSize(256, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.zavNumber_lE = QtGui.QLineEdit(self.groupBox)
        self.zavNumber_lE.setGeometry(QtCore.QRect(355, 50, 256, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zavNumber_lE.sizePolicy().hasHeightForWidth())
        self.zavNumber_lE.setSizePolicy(sizePolicy)
        self.zavNumber_lE.setMinimumSize(QtCore.QSize(256, 20))
        self.zavNumber_lE.setMaximumSize(QtCore.QSize(256, 20))
        self.zavNumber_lE.setObjectName("zavNumber_lE")
        self.zavNumber_lV = QtGui.QListView(self.groupBox)
        self.zavNumber_lV.setGeometry(QtCore.QRect(355, 85, 256, 125))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zavNumber_lV.sizePolicy().hasHeightForWidth())
        self.zavNumber_lV.setSizePolicy(sizePolicy)
        self.zavNumber_lV.setMinimumSize(QtCore.QSize(256, 125))
        self.zavNumber_lV.setMaximumSize(QtCore.QSize(256, 125))
        self.zavNumber_lV.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.zavNumber_lV.setObjectName("zavNumber_lV")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(9, 20, 170, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(170, 20))
        self.label.setMaximumSize(QtCore.QSize(170, 20))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.naimIzdel_cB = QtGui.QComboBox(self.groupBox)
        self.naimIzdel_cB.setGeometry(QtCore.QRect(145, 20, 190, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.naimIzdel_cB.sizePolicy().hasHeightForWidth())
        self.naimIzdel_cB.setSizePolicy(sizePolicy)
        self.naimIzdel_cB.setMinimumSize(QtCore.QSize(190, 20))
        self.naimIzdel_cB.setMaximumSize(QtCore.QSize(190, 20))
        self.naimIzdel_cB.setObjectName("naimIzdel_cB")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(9, 50, 60, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 20))
        self.label_2.setMaximumSize(QtCore.QSize(170, 20))
        self.label_2.setObjectName("label_2")
        self.model_cB = QtGui.QComboBox(self.groupBox)
        self.model_cB.setGeometry(QtCore.QRect(145, 50, 190, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_cB.sizePolicy().hasHeightForWidth())
        self.model_cB.setSizePolicy(sizePolicy)
        self.model_cB.setMinimumSize(QtCore.QSize(190, 20))
        self.model_cB.setMaximumSize(QtCore.QSize(190, 20))
        self.model_cB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.model_cB.setObjectName("model_cB")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(9, 85, 152, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(152, 20))
        self.label_3.setMaximumSize(QtCore.QSize(170, 20))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.firma_cB = QtGui.QComboBox(self.groupBox)
        self.firma_cB.setGeometry(QtCore.QRect(145, 85, 190, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firma_cB.sizePolicy().hasHeightForWidth())
        self.firma_cB.setSizePolicy(sizePolicy)
        self.firma_cB.setMinimumSize(QtCore.QSize(190, 20))
        self.firma_cB.setMaximumSize(QtCore.QSize(190, 20))
        self.firma_cB.setObjectName("firma_cB")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(9, 120, 152, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(152, 20))
        self.label_4.setMaximumSize(QtCore.QSize(170, 20))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.rezult_cB = QtGui.QComboBox(self.groupBox)
        self.rezult_cB.setGeometry(QtCore.QRect(145, 120, 190, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rezult_cB.sizePolicy().hasHeightForWidth())
        self.rezult_cB.setSizePolicy(sizePolicy)
        self.rezult_cB.setMinimumSize(QtCore.QSize(190, 20))
        self.rezult_cB.setMaximumSize(QtCore.QSize(190, 20))
        self.rezult_cB.setObjectName("rezult_cB")
        self.rezult_cB.addItem("")
        self.rezult_cB.addItem("")
        self.rezult_cB.addItem("")
        self.rezult_cB.addItem("")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(9, 155, 73, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(73, 20))
        self.label_5.setMaximumSize(QtCore.QSize(170, 20))
        self.label_5.setObjectName("label_5")
        self.operator_cB = QtGui.QComboBox(self.groupBox)
        self.operator_cB.setGeometry(QtCore.QRect(145, 155, 190, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operator_cB.sizePolicy().hasHeightForWidth())
        self.operator_cB.setSizePolicy(sizePolicy)
        self.operator_cB.setMinimumSize(QtCore.QSize(190, 20))
        self.operator_cB.setMaximumSize(QtCore.QSize(190, 20))
        self.operator_cB.setObjectName("operator_cB")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(9, 190, 37, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(37, 20))
        self.label_7.setMaximumSize(QtCore.QSize(170, 20))
        self.label_7.setObjectName("label_7")
        self.dateEdit = QtGui.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(145, 190, 190, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumSize(QtCore.QSize(190, 20))
        self.dateEdit.setMaximumSize(QtCore.QSize(190, 20))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.bd_tV = QtGui.QTableView(vkForm)
        self.bd_tV.setGeometry(QtCore.QRect(5, 268, 790, 327))
        self.bd_tV.setObjectName("bd_tV")
        self.layoutWidget = QtGui.QWidget(vkForm)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 237, 747, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.filter_cB = QtGui.QComboBox(self.layoutWidget)
        self.filter_cB.setMinimumSize(QtCore.QSize(200, 0))
        self.filter_cB.setObjectName("filter_cB")
        self.filter_cB.addItem("")
        self.filter_cB.addItem("")
        self.filter_cB.addItem("")
        self.filter_cB.addItem("")
        self.filter_cB.addItem("")
        self.filter_cB.addItem("")
        self.filter_cB.addItem("")
        self.filter_cB.addItem("")
        self.filter_cB.addItem("")
        self.horizontalLayout_2.addWidget(self.filter_cB)
        spacerItem = QtGui.QSpacerItem(55, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.search_pB = QtGui.QPushButton(self.layoutWidget)
        self.search_pB.setObjectName("search_pB")
        self.horizontalLayout_2.addWidget(self.search_pB)
        self.filter_lV = QtGui.QListView(vkForm)
        self.filter_lV.setGeometry(QtCore.QRect(410, 260, 256, 192))
        self.filter_lV.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.filter_lV.setObjectName("filter_lV")
        self.retranslateUi(vkForm)
        self.rezult_cB.setCurrentIndex(-1)
        self.filter_cB.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(vkForm)

    def retranslateUi(self, vkForm):
        vkForm.setWindowTitle(QtGui.QApplication.translate("vkForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("vkForm", "Форма входного контроля", None, QtGui.QApplication.UnicodeUTF8))
        self.print_pB.setText(QtGui.QApplication.translate("vkForm", "Печать формы", None, QtGui.QApplication.UnicodeUTF8))
        self.repeate_pB.setText(QtGui.QApplication.translate("vkForm", "Повторить", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_pB.setText(QtGui.QApplication.translate("vkForm", "Очистить", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("vkForm", "<html><head/><body><p>Список заводских номеров:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("vkForm", "Наименование изделия:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("vkForm", "Модель:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("vkForm", "<html><head/><body><p>Фирма-изготовитель:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("vkForm", "<html><head/><body><p>Результат контроля:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rezult_cB.setItemText(0, QtGui.QApplication.translate("vkForm", "ИСПРАВНО", None, QtGui.QApplication.UnicodeUTF8))
        self.rezult_cB.setItemText(1, QtGui.QApplication.translate("vkForm", "НЕИСПРАВНО", None, QtGui.QApplication.UnicodeUTF8))
        self.rezult_cB.setItemText(2, QtGui.QApplication.translate("vkForm", "ИСПРАВНЫ", None, QtGui.QApplication.UnicodeUTF8))
        self.rezult_cB.setItemText(3, QtGui.QApplication.translate("vkForm", "НЕИСПРАВНЫ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("vkForm", "Оператор:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("vkForm", "Дата:", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit.setDisplayFormat(QtGui.QApplication.translate("vkForm", "dd.MM.yy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("vkForm", "Фильтр запроса:", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_cB.setItemText(0, QtGui.QApplication.translate("vkForm", "Все", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_cB.setItemText(1, QtGui.QApplication.translate("vkForm", "Производитель", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_cB.setItemText(2, QtGui.QApplication.translate("vkForm", "Идентификационный номер", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_cB.setItemText(3, QtGui.QApplication.translate("vkForm", "Дата проверки", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_cB.setItemText(4, QtGui.QApplication.translate("vkForm", "Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_cB.setItemText(5, QtGui.QApplication.translate("vkForm", "Модель", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_cB.setItemText(6, QtGui.QApplication.translate("vkForm", "Результат проверки", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_cB.setItemText(7, QtGui.QApplication.translate("vkForm", "ФИО оператора", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_cB.setItemText(8, QtGui.QApplication.translate("vkForm", "Заводской номер", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("vkForm", "Запрос:", None, QtGui.QApplication.UnicodeUTF8))
        self.search_pB.setText(QtGui.QApplication.translate("vkForm", "Поиск", None, QtGui.QApplication.UnicodeUTF8))